// Worker entry point (wrangler.jsonc "main"): the OpenNext app for HTTP requests,
// plus the daily cron (wrangler.jsonc "triggers") for backups and log retention.
// `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.

// The build output may not exist yet (CI type-checks before building), hence ts-ignore.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: generated by `opennextjs-cloudflare build`
import { default as handler } from "./.open-next/worker.js";
import { runMaintenance, type MaintenanceEnv } from "./lib/maintenance";

// Durable Object classes the OpenNext build may define; re-exported so bindings keep working.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: generated by `opennextjs-cloudflare build`
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";

interface ScheduledContext {
  waitUntil(promise: Promise<unknown>): void;
}

const worker = {
  fetch: handler.fetch,
  async scheduled(_controller: unknown, env: MaintenanceEnv, ctx: ScheduledContext) {
    ctx.waitUntil(runMaintenance(env));
  },
};

export default worker;
